### ISSUE TITLE
Warning in console: "Function components cannot be given refs".

### ISSUE THREAD

**Issue by Johnrobmiller** [ankeetmaini/react-infinite-scroll-component#313]
I'm trying to use the infinite scroller component, but the console is giving me a warning about a mishandled ref which is apparently located within this library.  I'm unsure what I can do on my end to fix this, or whether this mishandled ref will cause any sneaky/hard to find problems or bugs.

Here's the error message in full:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of 'Link'.
    at Image1 (webpack-internal:///./node_modules/next/dist/client/image.js:321:20)
    at Link (webpack-internal:///./node_modules/next/dist/client/link.js:87:19)
    at div
    at Img (webpack-internal:///./src/components/Img.tsx:17:18)
    at div
    at div
    at div
    at div
    at InfiniteScroll (webpack-internal:///./node_modules/react-infinite-scroll-compon)
```

...and here's the unedited, raw code which created the warning:

```
<InfiniteScroll
          dataLength={itemCount}
          next={displayMoreBlogs}
          hasMore={hasMore}
          loader={ <h4>Loading</h4> }
        >
          {
            times(itemCount < blogDatas.length ? itemCount : blogDatas.length, Number).map(index => (
              <div key={index} className='mb:mx-auto mb:w-full dt:max-w-blog dt:ml-height-2'>
                <div className='flex mb:flex-col'>
                    <Img 
                      src={blogDatas[index].image} 
                      className='
                        border border-greyMid flex-shrink-0
                        mb:mx-auto mb:w-blogImg-mob 
                        dt:w-blogImg
                        cursor-pointer
                      '
                      width={blogDatas[index].imgDimentions.x}
                      height={blogDatas[index].imgDimentions.y}
                      href={'blogs/' + blogDatas[index].urlRoute}
                    />
                  <BlogText index={index} />
                </div>
                { index !== blogDatas.length - 1 && <Divider /> }
              </div>
            ))
          }
        </InfiniteScroll>```

**Comment by Johnrobmiller** [comment]
False alarm -- the error was caused by something else, not this library.
